[package]
name = "backend_absensi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
diesel = { version = "2.1.0", features = ["mysql"] }
dotenv = "0.15.0"
actix-web = "4"
